services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: bundle exec jekyll serve --watch --host 0.0.0.0
    ports:
      - '4000:4000'
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle